# Generated by Django 5.0.4 on 2025-05-16 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LlaveSeguridad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(editable=False, max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('iduser', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('contraseña', models.CharField(max_length=128)),
                ('llave', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.llaveseguridad')),
                ('tipouser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.tipouser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sadmin',
            fields=[
                ('iduser', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('contraseña', models.CharField(max_length=128)),
                ('llave', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.llaveseguridad')),
                ('tipouser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.tipouser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('iduser', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('contraseña', models.CharField(max_length=128)),
                ('llave', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.llaveseguridad')),
                ('tipouser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.tipouser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
