# Generated by Django 5.0.4 on 2025-05-16 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sadmin',
            new_name='SuperUser',
        ),
    ]
