# Generated by Django 5.0.4 on 2025-05-19 21:48

import productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=productos.models.ruta_imagen_producto),
        ),
    ]
