# Generated by Django 5.0.4 on 2025-05-19 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_publicacion_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('publicacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='productos.publicacion')),
            ],
        ),
    ]
